//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.08 at 10:32:20 AM CST 
//


package com.cxw.tool.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cxw.tool.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SAPolicyEnumFileTypeEnumsEnum_QNAME = new QName("", "enum");
    private final static QName _SAPolicyEnumFileTypeEnums_QNAME = new QName("", "fileTypeEnums");
    private final static QName _SAPolicyEnumEnums_QNAME = new QName("", "enums");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cxw.tool.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SAPolicyEnum }
     * 
     */
    public SAPolicyEnum createSAPolicyEnum() {
        return new SAPolicyEnum();
    }

    /**
     * Create an instance of {@link SAPolicyEnum.FileTypeEnums }
     * 
     */
    public SAPolicyEnum.FileTypeEnums createSAPolicyEnumFileTypeEnums() {
        return new SAPolicyEnum.FileTypeEnums();
    }

    /**
     * Create an instance of {@link SAPolicyEnum.Enums }
     * 
     */
    public SAPolicyEnum.Enums createSAPolicyEnumEnums() {
        return new SAPolicyEnum.Enums();
    }

    /**
     * Create an instance of {@link SAPolicyEnum.FileTypeEnums.Enum }
     * 
     */
    public SAPolicyEnum.FileTypeEnums.Enum createSAPolicyEnumFileTypeEnumsEnum() {
        return new SAPolicyEnum.FileTypeEnums.Enum();
    }

    /**
     * Create an instance of {@link SAPolicyEnum.Enums.Enum }
     * 
     */
    public SAPolicyEnum.Enums.Enum createSAPolicyEnumEnumsEnum() {
        return new SAPolicyEnum.Enums.Enum();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAPolicyEnum.FileTypeEnums.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = SAPolicyEnum.FileTypeEnums.class)
    public JAXBElement<SAPolicyEnum.FileTypeEnums.Enum> createSAPolicyEnumFileTypeEnumsEnum(SAPolicyEnum.FileTypeEnums.Enum value) {
        return new JAXBElement<SAPolicyEnum.FileTypeEnums.Enum>(_SAPolicyEnumFileTypeEnumsEnum_QNAME, SAPolicyEnum.FileTypeEnums.Enum.class, SAPolicyEnum.FileTypeEnums.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAPolicyEnum.FileTypeEnums }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileTypeEnums", scope = SAPolicyEnum.class)
    public JAXBElement<SAPolicyEnum.FileTypeEnums> createSAPolicyEnumFileTypeEnums(SAPolicyEnum.FileTypeEnums value) {
        return new JAXBElement<SAPolicyEnum.FileTypeEnums>(_SAPolicyEnumFileTypeEnums_QNAME, SAPolicyEnum.FileTypeEnums.class, SAPolicyEnum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAPolicyEnum.Enums }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enums", scope = SAPolicyEnum.class)
    public JAXBElement<SAPolicyEnum.Enums> createSAPolicyEnumEnums(SAPolicyEnum.Enums value) {
        return new JAXBElement<SAPolicyEnum.Enums>(_SAPolicyEnumEnums_QNAME, SAPolicyEnum.Enums.class, SAPolicyEnum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SAPolicyEnum.Enums.Enum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enum", scope = SAPolicyEnum.Enums.class)
    public JAXBElement<SAPolicyEnum.Enums.Enum> createSAPolicyEnumEnumsEnum(SAPolicyEnum.Enums.Enum value) {
        return new JAXBElement<SAPolicyEnum.Enums.Enum>(_SAPolicyEnumFileTypeEnumsEnum_QNAME, SAPolicyEnum.Enums.Enum.class, SAPolicyEnum.Enums.class, value);
    }

}
